trigger:
- develop
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Environment Setup'
  inputs:
    version: '10.16.3'

- task: Npm@1
  displayName: 'Installing Server Dependencies'
  inputs:
    command: 'install'
    workingDir: 'server'

- task: Npm@1
  displayName: 'Server Unit Tests'
  inputs:
    command: 'custom'
    workingDir: 'server'
    customCommand: 'run coverage'

- task: Npm@1
  displayName: 'Installing Client Dependencies'
  inputs:
    command: 'install'
    workingDir: 'client'

- task: Npm@1
  displayName: 'Client Unit Tests'
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'run coverage'

- task: Npm@1
  displayName: 'Building Server'
  inputs:
    command: 'custom'
    workingDir: 'server'
    customCommand: 'run build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Server.CurrentWorkingDirectory)/server/dist'
    artifact: 'Server Build'
    publishLocation: 'pipeline'
